### ISSUE TITLE
Add delete protection for events, projections, scenarios and strategies

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#129]
when an event, projection or strategy is used in a scenario, user should not be able to delete.

**Comment by GundulaW** [comment]
This is also linked to issue #78 in FloodAdapt-GUI "Standard events, projections and strategies"

**Comment by GundulaW** [comment]
Panos has ideas on this and an example

**Comment by kathrynroscoe** [comment]
Make sure that you allow the freedom to remove any scenario that is not used in a benefit analysis, regardless if it has already run or not!

**Comment by kathrynroscoe** [comment]
Also: A pop-up box should appear letting the user know why they can't delete what they are trying to delete.
