### ISSUE TITLE
Add rainfall increase for event with rainfall map or timeseries

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#143]
### Kind of request

Changing existing functionality

### Enhancement Description

Apply rainfall increase and storm frequency increase from projections to event sets
see old version for inspiration: https://github.com/Deltares/CFRSS/blob/main/scripts/integrator_sfincs.py

### Task list

- [x] add rainfall increase option to rainfall map or timeseries option in event

**Comment by dladrichem** [comment]
Connected to #169
