### ISSUE TITLE
Create metrics table in output tab

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares/FloodAdapt#162]
### Kind of request

Adding new functionality

### Enhancement Description

In addition to the infographic, we also want to have a table with metrics. This gives the FloodAdapt user a lot of flexibility to get summarizing information on any metrics they are interested in, even if they don't fit in the infographic template. For example, Charleston was recently interested in how much of the residential damage was due to just structural damage (so excluding the content damage). This would not fit in the infographic but could be added to the metrics table. 

The metrics table will also be useful in comparing scenarios (when we create a scenario comparison tab). I am trying to add a pic below, hopefully that works. 

![image](https://github.com/Deltares/FloodAdapt/assets/79269966/f1525bf4-3950-464e-837a-9e6a0c6f9b5b)

### Task list

* Decide where this functionality should sit
* Create a configuration file for selecting the metrics from the Delft-FIAT metrics output that should appear in the table and the name it should have

### Use case

See the enhancement description!

**Comment by GundulaW** [comment]
@kathrynroscoe I thought there is already a configuration file that describes, which output metrics the FIAT postprocessing file should create. I would refrain from making too many configuration files. The user will at some point not understand anymore, which one does what.

Currently we have on for each:

- FloodAdapt
- FIAT
- infographic
- impact metrics

**Comment by GundulaW** [comment]
connected to [https://github.com/Deltares/FloodAdapt-GUI/issues/61](url)

**Comment by GundulaW** [comment]
@Daley, you can use the Guitares listbox. An example for this is the scenario list in the scneario tab. Panos created that so please direct questions to him. If he is on holiday, I will try to help.

**Comment by dladrichem** [comment]
Round output to the nearest integer
