### ISSUE TITLE
Create a log file for scenario simulation progress

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares/FloodAdapt#196]
### Kind of request

Adding new functionality

### Enhancement Description

Create a log file like we used to have with calculation steps so a user can see what has happened, how long it took, and where it breaks down when it doesn't complete a simulation. 

[CFRSS.log](https://github.com/Deltares/FloodAdapt/files/12358877/CFRSS.log)

### Task list

* Check logging within SFINCS and Delft-FIAT
* If logging is available, forward to a FloodAdapt log file

**Comment by GundulaW** [comment]
@dladrichem , can you add log information on the FIAT post-processing?

**Comment by dladrichem** [comment]
Added the issue to the fiat_toolbox
