### ISSUE TITLE
Metrics CSV output should be transposed

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares/FloodAdapt#207]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

The output should have the 'header' on the top (Description, show in metrics table, long name, value), and the values on the vertical. This is only for the output metrics csv, not the aggregation-level output metrics csv.

### Current behaviour

The output should have the 'header' on the top (Description, show in metrics table, long name, value), and the values on the vertical. This is only for the output metrics csv, not the aggregation-level output metrics csv.

### Desired behaviour

The output should have the 'header' on the top (Description, show in metrics table, long name, value), and the values on the vertical. This is only for the output metrics csv, not the aggregation-level output metrics csv.

### Task list

The output should have the 'header' on the top (Description, show in metrics table, long name, value), and the values on the vertical. This is only for the output metrics csv, not the aggregation-level output metrics csv.

**Comment by dladrichem** [comment]
This is fixed in the fiat toolbox
